security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Infrastructure\Storage\Entity\User
                property: username
    firewalls:
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/
            stateless: true
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: /token/refresh

    access_control:
        - { path: ^/(login|token/refresh), roles: PUBLIC_ACCESS }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
